### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by traverseda** [traverseda/ChiiDB#2]
A very rough roadmap of the project.

- [ ] Implement a DSL for filtering/transforming data
    - [ ]  Assess the viability of webassembly as that DSL
    - [ ] Define the API for the DSL to access objects
 - [ ] Implement basic query runner, basically just map-reduce until we get the DSL up and running.
 - [ ] Implement support for changefeeds.

---

 - [ ] Implement something that can transform something sql-like into our DSL.
 - [ ] Implement API endpoints over sockets and http. Probably using python-hug
 - [ ] Implement permission manager
 - [ ] Implement replication system.
